package com.example.quickcode.common.validator;

public enum ErrorType {
    FIELD_REQUIRED,
    FIRST_LETTER_MUST_BE_CAPITALIZED,
    DIGITS_ARE_NOT_ALLOWED,
    SPECIAL_CHARS_ARE_NOT_ALLOWED,
    INCORRECT_EMAIL,
    ACCOUNT_WITH_THIS_EMAIL_ALREADY_EXISTS,
    PHONE_NUMBER_IS_TOO_SHORT,
    PASSWORD_LENGTH_IS_TOO_SHORT,
    PASSWORD_MUST_CONTAINS_LOWER_CASE,
    PASSWORD_MUST_CONTAINS_UPPER_CASE,
    PASSWORD_MUST_CONTAINS_DIGIT,
    PASSWORD_MUST_CONTAINS_SPECIAL_CHAR,
    PASSWORDS_ARE_NOT_THE_SAME, PHONE_NUMBER_ALREADY_USED,
}
